version: 2.1

jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout 
      - setup_remote_docker
      - run:
          name: Install dependencies 
          command: |
             docker build -t placidef/docker-reactjs -f Dockerfile.dev .

      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths: 
            - /caches/app.tar
      - run:
          name: run docker
          command: |
            docker run placidef/docker-reactjs npm run test -- --coverage













    

   